### ISSUE TITLE
Distinguish between control structures and blocks

### ISSUE THREAD

**Issue by thinkclay** [github/swift-style-guide#29]
First of all, let me say that I've read the guidelines, and this isn't a debate about aesthetics, but rather addressing the readability of a program and being able to quickly and easily discern intent. Reading quickly through code it's hard to distinguish a control structure from a block param:

    if foo {
        \\ code
    }

    foo {
        \\ code
    }

Whereas, if control structures always had open brackets on the new line, there would be far less oversight when reading:

    if foo
    {
        \\ code
    }

    foo {
        \\ code
    }

Another argument for distinguishing between control structures and closures is that "return" behaves differently in the two different cases. If you "return" from a control structure, it returns for the entire method / function. If you return within a closure, it only returns for that closure. The newline bracket makes it a bit easier to understand the scope of the return.

The main problem with the newline is distinguishing when it makes sense to indent. Partial adoption of newline brackets for just **some** control structures vs **all** could get messy. It might make sense to take an official stance and preference of Allman style.

**Comment by robrix** [comment]
Trailing closure synax exists precisely to make it look and act approximately like a control structure. This isn’t the style we follow, and I’m personally strongly :-1:

**Comment by jspahrsummers** [comment]
I agree :100:% with @robrix.

**Comment by thinkclay** [comment]
Feel free to close, just offering up opinions based on what I've seen with running SwiftCast.TV and interacting with new swift devs. More seasoned developers won't struggle with distinguishing between the two as much, so I guess it's not super relevant to all.

**Comment by robrix** [comment]
@thinkclay If it would help your organization, I’d encourage you to fork the style guide—we always intended this to inspire similar documents tailored to each team’s needs, rather than to speak for the community in general. We’ve certainly benefitted from its existence.
