### ISSUE TITLE
Leave a blank line after the opening brace of a class definition

### ISSUE THREAD

**Issue by lexrus** [github/swift-style-guide#43]
Just like what Apple did:
``` swift
/*! @class RPScreenRecorder
 @abstract Singleton class used to control app recording.
 */
public class RPScreenRecorder : NSObject {
    
    /* @abstract Shared instance of the screen recorder. */
    public class func sharedRecorder() -> RPScreenRecorder
//...
```

Furthermore, there's a white space after the class name.

_Rationale:_ I think this looks elegant.

**Comment by robrix** [comment]
Thanks for the suggestion!

We try not to add to the style guide proactively. If we run into a disagreement during code review, we’ll discuss adding to it then; but this isn’t something we’ve had any contention around thus far.

Therefore, I’d prefer to leave this out of our guide (at least for now). However, please feel free to fork & add to the style guide if this would be valuable to your projects!
