### ISSUE TITLE
Force-Unwrapping of Optionals

### ISSUE THREAD

**Issue by matrinox** [github/swift-style-guide#44]
IMO, it's better to use `optional!` for things that are definitely not nil so that a developer can catch these errors instead of silently hiding it.

Examples:
```swift
// You should know right away if you spelled it incorrectly or the file does not exist
let image = UIImage("fileName")!

// When a method is used to process non-empty collections (good idea to put a guard statement that traps or throws if count is 0)
func processSelectedItems(selectedItems: [Item]) {
  let firstItem = selectedItems.first!
}

// UI elements that must always be connected in IB
@IBOutlet var usernameField: UITextField!

// A function that returns an optional but you know will not return nil for the given input
let result = alwaysReturnsNonNilForGivenInput("valid input")!
```

**Comment by poisonedslo** [comment]
You should optionally unwrap these values and use asserts to test them. That way, you get a runtime error in debug build, while avoiding runtime errors in release builds.

Missing image is bad, but runtime errors should be avoided at all costs.

**Comment by matrinox** [comment]
The above code also acts as an automatic assert. In development without optimizations turned on, nil images will trigger a runtime error, similar to writing an assert but less wordy. The only difference is that it will not fail silently.

**Comment by robrix** [comment]
This guide is intended to be descriptive (i.e. a log of the consensus that GitHub’s Swift developers have come to, where necessary), rather than prescriptive. We haven’t felt the need to prescribe this either way thus far, so I’m going to close this out.
