### ISSUE TITLE
Why are there spaces in dictionary literal?

### ISSUE THREAD

**Issue by mgrebenets** [github/swift-style-guide#47]
Why are there extra spaces after `[` and before `]` in dictionary literal example?

```
[ Sweden: Stockholm ]
```

This style disagrees with Apple's own books, what's more strange, it disagrees with the type declaration used on the same line `[Country: City]`.
It also mismatches the use of arrays in Swift.

In other words, looks like some Objective-C got through the cracks into a Swift guideline.

**Comment by akashivskyy** [comment]
I noticed that as well, but assumed this was made to purposefully differentiate between the space-less type declaration and the contents of a literal.

amiright?

**Comment by joshaber** [comment]
>but assumed this was made to purposefully differentiate between the space-less type declaration and the contents of a literal.

Right.

Generally this document is descriptive, not prescriptive. It describes the style those of us who write Swift at GitHub can agree on.
