### ISSUE TITLE
Implicit vs. Explicit

### ISSUE THREAD

**Issue by Gouldsc** [github/swift-style-guide#52]
It seems this style is heavy on implicit conventions. For example omitting "get" on computed properties. The stated reason for this was "The intent and meaning of the first version is clear, and results in less code." Just to be clear, there is the same amount of code, it's simply the case that it's IMPLIED code that's invisible. The reader still has to mentally substitute the code into what's on screen each time they read it.

My personal preference is to generally be explicit in most cases. It makes the intention of the programmer clearer to the reader of the code (which is different than the intent of the code itself), avoids assumptions/makes assumptions more obvious, and lowers the bar for who can open the file and immediately grok what's going on. Again, this is simply my opinion (and I don't expect to convert anyone to my point of view), but I don't think omissions such as these are actually reducing the amount of code in a meaningful way (there are admittedly fewer keystrokes). The "less code is better" mantra as I understand it applies more to avoiding redundancy, YAGNI, keeping classes (and structs/enums), functions and methods small and focused, etc. than trying to keep your code as terse as possible by omitting optional keywords, punctuation, etc. at nearly every opportunity.

Perhaps it is better style to omit "get" on computed properties, but the stated rationale should be something along the lines of "terse code is better" because that better reflects the values underlying this style guide and also because invoking the "less code" mantra is kind of a distortion of that coding principle.

Overall there's a lot to like here, but I just thought I'd bring this up. Brevity does have a cost.

**Comment by mdiep** [comment]
Brevity is an important part of clarity. I think the stated reason is fine and correct.

But this is our team's coding style. It's okay if you disagree. In that case, we'd encourage you to fork our style guide and create your own! :smile:
